<p>You can also use EnlighterJS to display a set of different codes within a tab-pane</p>
<h4>Example</h4>

<pre>
[codegroup]
 	[js tab="Javascript Message"]
	window.addEvent('domready', function(){
		// display string on console
		console.info('Hello Enlighter');
		
		// show element
		$('#myelement').show();
	});	
	[/js]
	
	[html]
	&lt;div id="myelement"&gt;
	INITIALIZATION START
	&lt;/div&gt;		
	[/html]
	
	[css tab="Styling"]
	#myelement{
		color: #cc2222;
		padding: 15px;
		font-size: 20px;
		text-align: center;		
	}		
	[/css]	
[/codegroup]
</pre>

<p><strong>Syntax: </strong> <code>[codegroup theme=""] [js tab=""]...[/js] [css]...[/css] ... [/codegroup]</code></p>

<p><strong>Attributes</strong></p>
<p>
<ul style="padding-left: 10px">
    <li><strong>theme</strong> (optional) - defines the theme that should used, will overwrite the settings-page values
    </li>
    <li><strong>tab</strong> (optional) - set the name of the tab-pane, if not defined the language name will be used as
        title
    </li>
</ul></p>
