<p>Enlighter supports markdown style fenced code blocks in your post, pages, comments and bbpress.<br/>
    <strong><em>You should not use this feature in Visual-Editor Mode!</em></strong>
</p>
<h4>Code Block Examples</h4>
<p>
<pre>
```php
if (version_compare(phpversion(), '5.3', '>=')){
    echo 'Hello World';
}
```
</pre>
<pre>
```
console.log('Generic Highlighting');
```
</pre></p>

<h4>Inline Example</h4>
<p>
<pre>
This is a inline code `console.log('snippet');`.
</pre>

<h4>Inline Example with language identifier</h4>
<p>
<pre>
This is a javascript inline code `console.log('snippet');`js :)
</pre>
