<p><strong>Enlighter Tutorials</strong></p>

<p>The following Tutorials will help you to getting started with Enlighter!</p>

<hr />

<ul>
    <li><a href="https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_VisualEditor.md" target="_blank">Enlighter Visual Editor Usage</a></li>
    <li><a href="https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_Markdown.md" target="_blank">Enlighter Markdown Usage</a></li>

</ul>