<p>Enlighter has three different methods to mark code blocks to be highlighted. These methods are related to the editor mode your are using!</p>

<hr />

<p><strong>Visual Editor Mode</strong></p>
<p>Enlighter provides a full integration into the visual editor! You can easily add code snippets by using the <strong>Code Insert Dialog</strong> located in the upper right corner of the editor toolbar.<br />
By focusing a code block in the visual editor, a edit icon will appear - this allows you to change the preferences of this snippet.</p>
This mode allows you to use Enlighter without any worries. But take care: do not copy+paste snippets directly in the editor!</p>

<p>It is <strong>not recommended</strong> to use shortcodes and/or markdown syntax in this mode, because the editor will interpret this sections as regular content and is adding p/br tags into your code.</p>
<hr />

<p><strong>Text/HTML Mode</strong></p>
<p>In this mode, you are allowed to post plain text/html. There are no additional tags which are added to the editor. The recommended editing methods for this mode are:</p>
<ul>
    <li>Shortcode like <code>[php]echo "Hello World";[/php]</code></li>
    <li>Markdown like <code>`echo "Hello World";`</code></li>
</ul>
