<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="postbox">
<h3 class="hndle"><?php _e('Enlighter Related', 'enlighter'); ?></h3>
<div class="inside">
<!-- Metabox-Content -->
<p><?php _e('Got a problem ? Need support or want to request a new feature ?', 'enlighter'); ?></p>
<ul>
    <li><a target="_new" href="https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs">Docs and Tutorials</a></li>
    <li><a target="_new" href="https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs/FAQ.md">FAQ</a></li>
    <li><a target="_new" href="https://enlighterjs.org/Themes.html">Theme Demo</a></li>
    <li><a target="_new" href="https://wordpress.org/support/plugin/enlighter">Support Forum</a></li>
    <li><a target="_new" href="https://twitter.com/andidittrich">News on Twitter</a></li>
    <li><a target="_new" href="https://wordpress.org/plugins/enlighter/">Enlighter on WordPress.org</a></li>
    <li><a target="_new" href="https://github.com/EnlighterJS/Plugin.WordPress/issues">Report a Bug</a></li>
    <li><a target="_new" href="https://andidittrich.de/">Author`s Website</a></li>
    <li><a target="_new" href="<?php echo admin_url('admin.php?page=Enlighter-About'); ?>">About Enlighter</a></li>
</ul>
<!-- // Metabox-Content -->
</div></div>